### ISSUE TITLE
Inconsistent formatting for the Total values

### ISSUE THREAD

**Issue by sallymoc** [qubic/qx-frontend#2]
Current behaviour: In some cases "qu" suffix is added, in some cases just the value is displayed

![image](https://github.com/user-attachments/assets/50785534-67fa-49c4-9403-260666efb88d)
![image](https://github.com/user-attachments/assets/4e5a99e0-a648-4292-849a-4b1d993f2171)

Expected behaviour:
Considering the amount is always in same currency, I would add this to the title i.e "Total (QUBIC)". 
I would do the same for the unit price "Price (QUBIC)"
Also, I would suggest to have these numbers right aligned.

**Comment by alexmf91** [comment]
Fixed on https://github.com/qubic/qx-frontend/pull/4

**Comment by sallymoc** [comment]
Verified in the live version
